server {
    listen 80;
    server_name _;

    # m3u 文件
    location / {
        root /var/www/html;
        index index.html;
        # 允许跨域
        add_header Access-Control-Allow-Origin *;
    }

    # m3u 文件添加正确的 Content-Type
    location ~ \.m3u$ {
        root /var/www/html;
        add_header Content-Type application/vnd.apple.mpegurl;
        add_header Access-Control-Allow-Origin *;
    }
}
